import { ArrowLeft, ShieldCheck, Lock, EyeOff, Server, Database } from "lucide-react";

interface PrivacyPolicyProps {
  onBack: () => void;
}

export function PrivacyPolicy({ onBack }: PrivacyPolicyProps) {
  return (
    <div className="max-w-4xl mx-auto py-10 px-4 sm:px-6 space-y-8 animate-in fade-in duration-200">
      <div className="flex items-center justify-between pb-6 border-b border-slate-200">
        <div>
          <button
            type="button"
            onClick={onBack}
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900 transition-colors mb-3 cursor-pointer"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to App</span>
          </button>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">Privacy Policy</h1>
          <p className="text-sm text-slate-500 mt-1">Creative DNA for ChatGPT & OpenAI Apps SDK &bull; Last updated: September 18, 2026</p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-medium">
          <ShieldCheck className="w-4 h-4" />
          <span>Strict Read-Only Privacy</span>
        </div>
      </div>

      <div className="prose prose-slate max-w-none text-slate-700 text-sm leading-relaxed space-y-6">
        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <Lock className="w-4 h-4 text-indigo-600" />
            1. Overview & Core Privacy Commitment
          </h2>
          <p>
            Creative DNA is an authoritative brand creative intelligence service designed specifically for ChatGPT, OpenAI Apps SDK, and custom AI agents.
            Our service is strictly <strong>read-only</strong>. We do not require, request, collect, store, or sell personal user information, chat histories, or session credentials.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <EyeOff className="w-4 h-4 text-indigo-600" />
            2. Data We Do NOT Collect
          </h2>
          <ul className="list-disc pl-5 space-y-1.5">
            <li><strong>No User Chat Logs:</strong> Conversations between users and ChatGPT are never relayed, stored, or reviewed on our servers.</li>
            <li><strong>No Personal Identifiers:</strong> We do not ask for names, email addresses, phone numbers, or payment credentials.</li>
            <li><strong>No Tracking Cookies:</strong> The gateway does not set behavioral cookies, cross-site trackers, or advertising beacons.</li>
            <li><strong>No Generative Retention:</strong> Output generated by ChatGPT using Creative DNA rules is not retained or harvested.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <Server className="w-4 h-4 text-indigo-600" />
            3. Ephemeral Request Handling
          </h2>
          <p>
            When a user asks ChatGPT to apply a brand&apos;s Creative DNA, ChatGPT calls our Model Context Protocol (MCP) endpoint (<code>POST /api/mcp</code>) or REST API (<code>POST /api/resolve</code>).
            These requests contain only the brand identifier (e.g. <code>PawfectHouse</code>) and the branch name (e.g. <code>Onepage</code>).
            Requests are executed statelessly in memory and discarded immediately upon transmitting the canonical creative specification response.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
            <Database className="w-4 h-4 text-indigo-600" />
            4. Upstream Data Source & Security
          </h2>
          <p>
            The canonical source of truth for Creative DNA brand guidelines is hosted on an isolated, secure cloud datastore.
            The Creative DNA Gateway communicates with this upstream source via encrypted HTTPS requests using public read-only functions.
            No private database credentials or administrative permissions exist within the gateway runtime.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-slate-900">5. OpenAI Apps SDK & ChatGPT Directory Compliance</h2>
          <p>
            Creative DNA strictly abides by OpenAI&apos;s Developer Guidelines and Privacy Standards. We adhere to the principle of minimal data access, granting ChatGPT read-only access exclusively to public brand creative design rules.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-slate-900">6. Contact & Data Inquiries</h2>
          <p>
            For privacy inquiries, security questions, or verification regarding Creative DNA, please contact our privacy compliance team at:
            <br />
            <a href="mailto:support@creative-dna-gateway.vercel.app" className="text-indigo-600 hover:text-indigo-800 font-medium">
              support@creative-dna-gateway.vercel.app
            </a>
          </p>
        </section>
      </div>

      <div className="pt-6 border-t border-slate-200">
        <button
          type="button"
          onClick={onBack}
          className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold hover:bg-slate-800 transition-colors"
        >
          Return to Creative DNA
        </button>
      </div>
    </div>
  );
}
